FROM golang:1.25

RUN apt update
RUN apt install -y psmisc iproute2 net-tools iputils-ping pipx
RUN pipx install tldr && ln -s /root/.local/bin/tldr /usr/local/bin/tldr
RUN go install github.com/go-delve/delve/cmd/dlv@latest